### ISSUE TITLE
Cannot restore a backup from external storage

### ISSUE THREAD

**Issue by Dartoxian** [nextcloud/backup#203]
Backup from external storage cannot be restored following the instructions in the README. The following error occurs:

```
www-data@7181917e915b:~/html$ ./occ backup:point:download --external 3 --no-check 20220301110502-full-XO8VEB1t5luK9sv
> found a local restoring point
An unhandled exception has been thrown:
Error: Call to a member function isLock() on null in /var/www/html/custom_apps/backup/lib/Command/PointDownload.php:216
Stack trace:
#0 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Backup\Command\PointDownload->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Backup\Command\PointDownload), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/console.php(99): OC\Console\Application->run()
#7 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

I am running Nextcloud 23.0.2 with the backups app 1.0.4. It seems the metadataService in https://github.com/nextcloud/backup/blob/master/lib/Command/PointDownload.php is not initialised.

**Comment by dffvb** [comment]
Have the same problem
