### ISSUE TITLE
TypeError: OCA\Backup\Service\ConfigService::getSystemValue(): Return value must be of type string, array returned in /var/www/nextcloud/apps2/backup/lib/Service/ConfigService.php:240

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/backup#26]
Backup Master
Server master 23

``` php
occ backup:point:create       
An unhandled exception has been thrown:
TypeError: OCA\Backup\Service\ConfigService::getSystemValue(): Return value must be of type string, array returned in /var/www/nextcloud/apps2/backup/lib/Service/ConfigService.php:240
Stack trace:
#0 /var/www/nextcloud/apps2/backup/lib/Service/PointService.php(423): OCA\Backup\Service\ConfigService->getSystemValue('apps_paths')
#1 /var/www/nextcloud/apps2/backup/lib/Service/PointService.php(397): OCA\Backup\Service\PointService->addCustomApps(Object(OCA\Backup\Model\RestoringPoint))
#2 /var/www/nextcloud/apps2/backup/lib/Service/PointService.php(368): OCA\Backup\Service\PointService->addingRestoringData(Object(OCA\Backup\Model\RestoringPoint), true)
#3 /var/www/nextcloud/apps2/backup/lib/Service/PointService.php(232): OCA\Backup\Service\PointService->initRestoringPoint(true)
#4 /var/www/nextcloud/apps2/backup/lib/Command/PointCreate.php(101): OCA\Backup\Service\PointService->create(true)
#5 /var/www/nextcloud/apps2/mail/vendor/symfony/console/Command/Command.php(255): OCA\Backup\Command\PointCreate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/nextcloud/apps2/mail/vendor/symfony/console/Application.php(1000): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/nextcloud/apps2/mail/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Backup\Command\PointCreate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nextcloud/apps2/mail/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#12 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
```

## `occ config:list`
```json
{
    "system": {
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/nextcloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "loglevel": 1,
        "debug": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\AVI",
            "OC\\Preview\\BMP",
            "OC\\Preview\\Font",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Image",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MKV",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MP4",
            "OC\\Preview\\MSOffice",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\PNG",
            "OC\\Preview\\SGI",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TGA",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\TXT",
            "OC\\Preview\\XBitmap"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dev.skjnldsv.com",
            "192.168.1.100",
            "web"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.0.5",
        "overwrite.cli.url": "http:\/\/web",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "vueexample",
            "browser_warning",
            "gallery",
            "impersonate",
            "documentserver_community",
            "onlyoffice",
            "pride"
        ],
        "theme": "",
        "maintenance": false,
        "mail_template_class": "OCA\\AmxBranding\\EMailTemplate",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.server.url": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.15.0",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes"
        },
        "amx_branding": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "announcementcenter": {
            "enabled": "no",
            "installed_version": "6.0.0-dev.1",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "14"
        },
        "backup": {
            "enabled": "yes",
            "installed_version": "1.0.0-beta1",
            "mockup_date": "1635553610",
            "types": ""
        },
        "browser_warning": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.3.0-RC.1",
            "types": ""
        },
        "circles": {
            "enabled": "yes",
            "installed_version": "23.0.0-dev",
            "loopback_tmp_id": "",
            "loopback_tmp_scheme": "http",
            "maintenance_run": "0",
            "maintenance_update": "{\"maximum\":3,\"3\":1634580840,\"2\":1634580840,\"1\":1634580840}",
            "migration_22": "1",
            "migration_run": "0",
            "test_nc_base": "",
            "types": "filesystem,dav"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "4.0.1",
            "types": "dav"
        },
        "contactsinteraction": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": "dav"
        },
        "core": {
            "installedat": "1622184564.6025",
            "lastcron": "1635337868",
            "lastupdateResult": "[]",
            "lastupdatedat": "0",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_restrict_user_enumeration_full_match": "no",
            "shareapi_restrict_user_enumeration_to_group": "no",
            "shareapi_restrict_user_enumeration_to_phone": "no",
            "theming.variables": "b92d206521717ac032f8aa58d3c7ff2f",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.3.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.21.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "documentserver_community": {
            "enabled": "no",
            "installed_version": "0.1.11",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "authentication"
        },
        "files": {
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_cmd_options": "",
            "av_host": "",
            "av_infected_action": "delete",
            "av_max_file_size": "-1",
            "av_mode": "executable",
            "av_path": "\/usr\/bin\/clamscan",
            "av_port": "0",
            "av_socket": "\/var\/run\/clamav\/clamd.ctl",
            "av_stream_max_length": "26214400",
            "enabled": "no",
            "installed_version": "3.2.1",
            "types": "filesystem,dav"
        },
        "files_downloadcounter": {
            "download_count_SKiTo55fFPCoa4n": "1",
            "download_limit_SKiTo55fFPCoa4n": "20",
            "enabled": "no",
            "installed_version": "0.0.1",
            "types": ""
        },
        "files_downloadlimit": {
            "enabled": "yes",
            "installed_version": "0.0.1",
            "types": ""
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "yes",
            "installed_version": "1.15.0",
            "lookupServerEnabled": "no",
            "lookupServerUploadEnabled": "no",
            "outgoing_server2server_share_enabled": "yes",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.16.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.12.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.5.0",
            "types": ""
        },
        "guests": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "authentication"
        },
        "hmr_enabler": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "impersonate": {
            "enabled": "no",
            "installed_version": "1.9.0",
            "types": ""
        },
        "integration_github": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": ""
        },
        "integration_twitter": {
            "installed_version": "1.0.1",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "1.11.0-alpha.1",
            "types": ""
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "4.1.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.11.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "authentication"
        },
        "onlyoffice": {
            "DocumentServerUrl": "https:\/\/dev.skjnldsv.com\/apps\/documentserver_community\/",
            "defFormats": "{\"docx\":true,\"pptx\":true,\"xlsx\":true,\"odp\":true,\"ods\":true,\"odt\":true,\"doc\":true,\"ppt\":true,\"xls\":true}",
            "editFormats": "{\"csv\":true,\"docx\":true,\"pptx\":true,\"txt\":true,\"xlsx\":true,\"odp\":true,\"ods\":true,\"odt\":true,\"rtf\":true}",
            "enabled": "no",
            "installed_version": "7.1.2",
            "sameTab": "true",
            "types": "filesystem"
        },
        "password_policy": {
            "enabled": "no",
            "installed_version": "1.12.0",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "pride": {
            "enabled": "no",
            "installed_version": "0.0.4",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "prevent_group_restriction"
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "13.0.0-dev",
            "types": "dav,prevent_group_restriction"
        },
        "support": {
            ***REMOVED SENSITIVE VALUE***
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.13.6",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.4.0",
            "types": "dav"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": ""
        },
        "user_ldap": {
            ***REMOVED SENSITIVE VALUE***
        },
        "user_oidc": {
            "enabled": "no",
            "id4me_enabled": "0",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "virtualfolder": {
            "enabled": "no",
            "installed_version": "0.1.0",
            "types": "filesystem"
        },
        "vueexample": {
            "enabled": "no",
            "installed_version": "6.0.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": "filesystem"
        }
    }
}
```

**Comment by ArtificialOwl** [comment]
right now, fixed by ignoring custom_apps folder, will fix this.
