### ISSUE TITLE
Unable to complete full backup over SFTP

### ISSUE THREAD

**Issue by Tha-Fox** [nextcloud/backup#264]
# Expected Behavior

Get a completed full backup over SFTP connection to external storage.

# Current Behavior

Backup fails after writing probably some metadata to external storage.

# Failure Information (for bugs)

## Steps to Reproduce

1. Install Nextcloud 23.0.2.
2. Install external storage and configure it with SFTP connection using username and password.
3. Install backup app 1.0.6 and set backups and temporary data to go to external storage.
4. Try to create a full backup.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Nextcloud version: 23.0.2
* Backup app version: 1.0.6

My Nextcloud instance is running on k3s cluster. It's been installed using Helm and fpm-alpine image.

I've been trying to back up my test instance, which includes only ~40MB of data. I have external storage as my backup target. It is an OpenWRT router with external USB disk attached to it. I have configured SFTP connection authenticating with username and password and limiting the external storage visibility to admin group only.

I have the following simple directory layout.

testnextcloud/
├─ app_data/
├─ backups/

External storage connects to testnextcloud and I can see both subdirectories in Nextcloud files. I can both create and upload files through Files app to app_data and backups directories.

## Failure Logs

When I run the backup, the end result is that it creates app.zip, which is about 42kB , to app_data and nothing else. In cli, I can see this:

```
/var/www/html # sudo -u www-data PHP_MEMORY_LIMIT=512M php occ backup:point:create
> maintenance mode: on
> initialization of the AppData
> initialization of the RestoringPoint: 20220411044257-full-ubcY2knwmqeVycR based on NC23.0.2.1
> initialization of the storage
> preparation of the data to be stored in the restoring point
> preparation of internal data
> maintenance mode: off
An unhandled exception has been thrown:
TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /var/www/html/lib/private/Files/Storage/Common.php:208
Stack trace:
#0 /var/www/html/lib/private/Files/Storage/Common.php(208): fwrite(false, '')
#1 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(258): OC\Files\Storage\Common->file_put_contents('app_data/202204...', '')
#2 /var/www/html/lib/private/Files/Storage/Wrapper/PermissionsMask.php(112): OC\Files\Storage\Wrapper\Wrapper->file_put_contents('app_data/202204...', '')
#3 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(258): OC\Files\Storage\Wrapper\PermissionsMask->file_put_contents('app_data/202204...', '')
#4 /var/www/html/lib/private/Files/Storage/Wrapper/Availability.php(274): OC\Files\Storage\Wrapper\Wrapper->file_put_contents('app_data/202204...', '')
#5 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(258): OC\Files\Storage\Wrapper\Availability->file_put_contents('app_data/202204...', '')
#6 /var/www/html/lib/private/Files/View.php(1169): OC\Files\Storage\Wrapper\Wrapper->file_put_contents('app_data/202204...', '')
#7 /var/www/html/lib/private/Files/View.php(706): OC\Files\View->basicOperation('file_put_conten...', '/admin/files/te...', Array, '')
#8 /var/www/html/lib/private/Files/Node/Folder.php(198): OC\Files\View->file_put_contents('/admin/files/te...', '')
#9 /var/www/html/lib/private/Files/SimpleFS/SimpleFolder.php(89): OC\Files\Node\Folder->newFile('restore.php', '')
#10 /var/www/html/custom_apps/backup/lib/Service/ChunkService.php(739): OC\Files\SimpleFS\SimpleFolder->newFile('restore.php', '')
#11 /var/www/html/custom_apps/backup/lib/Service/PointService.php(403): OCA\Backup\Service\ChunkService->copyApp(Object(OCA\Backup\Model\RestoringPoint))
#12 /var/www/html/custom_apps/backup/lib/Service/PointService.php(251): OCA\Backup\Service\PointService->initRestoringPoint(true)
#13 /var/www/html/custom_apps/backup/lib/Command/PointCreate.php(120): OCA\Backup\Service\PointService->create(true, '', '')
#14 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Backup\Command\PointCreate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Backup\Command\PointCreate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/console.php(99): OC\Console\Application->run()
#21 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

**Comment by Tha-Fox** [comment]
I "fixed" this by moving from SFTP to SMB/CIFS.

**Comment by castrelo02** [comment]
NC 24.0.4
Backup 113

I get the same error with remote storage by sftp. This storage works from NC files, accessing external storage.
I don't have possibility to use cifs

Any idea?

```
> maintenance mode: on
> initialization of the AppData
> initialization of the RestoringPoint: 20220905085730-full-cwsnFq9muHLAMoe based on NC24.0.4.1
> initialization of the storage
> preparation of the data to be stored in the restoring point
> preparation of internal data
> maintenance mode: off
An unhandled exception has been thrown:
TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /home/user/cloud/lib/private/Files/Storage/Common.php:209
Stack trace:
#0 /home/user/cloud/lib/private/Files/Storage/Common.php(209): fwrite(false, '')
#1 /home/user/cloud/lib/private/Files/Storage/Wrapper/Wrapper.php(258): OC\Files\Storage\Common->file_put_contents('backup/20220905...', '')
#2 /home/user/cloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php(112): OC\Files\Storage\Wrapper\Wrapper->file_put_contents('backup/20220905...', '')
#3 /home/user/cloud/lib/private/Files/Storage/Wrapper/Wrapper.php(258): OC\Files\Storage\Wrapper\PermissionsMask->file_put_contents('backup/20220905...', '')
#4 /home/user/cloud/lib/private/Files/Storage/Wrapper/Availability.php(274): OC\Files\Storage\Wrapper\Wrapper->file_put_contents('backup/20220905...', '')
[...]
```
