### ISSUE TITLE
Can't start Backup manually

### ISSUE THREAD

**Issue by defekT1312** [nextcloud/backup#636]
Hey, I'm currently have some Problems with the Backups overall and to troubleshoot it I want to start the Backup manually but I'm getting following Error:

`sudo -u www-data php /var/www/nextcloud/occ backup:point:create

> maintenance mode: on
> initialization of the AppData
> maintenance mode: off
An unhandled exception has been thrown:
TypeError: OC\Files\View::basicOperation(): Argument #2 ($path) must be of type string, null given, called in /var/www/nextcloud/lib/private/Files/View.php on line 528 and defined in /var/www/nextcloud/lib/private/Files/View.php:1128
Stack trace:
#0 /var/www/nextcloud/lib/private/Files/View.php(528): OC\Files\View->basicOperation()
#1 /var/www/nextcloud/lib/private/Files/Filesystem.php(545): OC\Files\View->file_exists()
#2 /var/www/nextcloud/apps/files_versions/lib/Storage.php(190): OC\Files\Filesystem::file_exists()
#3 /var/www/nextcloud/apps/files_versions/lib/Listener/FileEventsListener.php(196): OCA\Files_Versions\Storage::store()
#4 /var/www/nextcloud/apps/files_versions/lib/Listener/FileEventsListener.php(102): OCA\Files_Versions\Listener\FileEventsListener->write_hook()
#5 /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php(86): OCA\Files_Versions\Listener\FileEventsListener->handle()
#6 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(230): OC\EventDispatcher\ServiceEventListener->__invoke()
#7 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#8 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(94): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#9 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(106): OC\EventDispatcher\EventDispatcher->dispatch()
#10 /var/www/nextcloud/lib/private/Files/Node/HookConnector.php(100): OC\EventDispatcher\EventDispatcher->dispatchTyped()
#11 /var/www/nextcloud/lib/private/legacy/OC_Hook.php(105): OC\Files\Node\HookConnector->write()
#12 /var/www/nextcloud/lib/private/Files/View.php(1275): OC_Hook::emit()
#13 /var/www/nextcloud/lib/private/Files/View.php(1144): OC\Files\View->runHooks()
#14 /var/www/nextcloud/lib/private/Files/View.php(680): OC\Files\View->basicOperation()
#15 /var/www/nextcloud/lib/private/Files/Node/Folder.php(188): OC\Files\View->file_put_contents()
#16 /var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php(89): OC\Files\Node\Folder->newFile()
#17 /var/www/nextcloud/apps/backup/lib/Service/PointService.php(796): OC\Files\SimpleFS\SimpleFolder->newFile()
#18 /var/www/nextcloud/apps/backup/lib/Service/PointService.php(386): OCA\Backup\Service\PointService->initBackupFS()
#19 /var/www/nextcloud/apps/backup/lib/Service/PointService.php(252): OCA\Backup\Service\PointService->initRestoringPoint()
#20 /var/www/nextcloud/apps/backup/lib/Command/PointCreate.php(120): OCA\Backup\Service\PointService->create()
#21 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\Backup\Command\PointCreate->execute()
#22 /var/www/nextcloud/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#23 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#24 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#25 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#26 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#27 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#28 /var/www/nextcloud/occ(11): require_once('...')`

I'm trying to find help to this Problem now for 2 hours but without any succes unfortunateley.
I'm running a NextcloudPi instance on a Proxmox lxc, everything is up to date.

**Comment by hammy1988** [comment]
Hi @defekT1312,
which version of Nextcloud are you using? And have you set the app data to an external storage in the backup app? 
Because I have encountered the same error since I updated to Nextcloud version 28 (28.0.3) and started using the backup:point:upload command to transfer the backup data from local to external.

```
sudo -u www-data php occ backup:point:upload --generate-log [Restoring-Point-ID]

- uploading [Restoring-Point-ID] to external folders
 - checking external folder 24:/
  > restoring point not found
  * Creating Restoring Point on external folder: ok
  > restoring point created
  * initiating health check
An unhandled exception has been thrown:
TypeError: OC\Files\View::basicOperation(): Argument #2 ($path) must be of type string, null given, called in /var/www/html/lib/private/Files/View.php on line 528 and defined in /var/www/html/lib/private/Files/View.php:1128
Stack trace:
#0 /var/www/html/lib/private/Files/View.php(528): OC\Files\View->basicOperation('file_exists', NULL)
#1 /var/www/html/lib/private/Files/Filesystem.php(545): OC\Files\View->file_exists(NULL)
#2 /var/www/html/apps/files_versions/lib/Storage.php(190): OC\Files\Filesystem::file_exists(NULL)
#3 /var/www/html/apps/files_versions/lib/Listener/FileEventsListener.php(196): OCA\Files_Versions\Storage::store(NULL)
#4 /var/www/html/apps/files_versions/lib/Listener/FileEventsListener.php(102): OCA\Files_Versions\Listener\FileEventsListener->write_hook(Object(OC\Files\Node\File))
#5 /var/www/html/lib/private/EventDispatcher/ServiceEventListener.php(86): OCA\Files_Versions\Listener\FileEventsListener->handle(Object(OCP\Files\Events\Node\BeforeNodeWrittenEvent))
#6 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(230): OC\EventDispatcher\ServiceEventListener->__invoke(Object(OCP\Files\Events\Node\BeforeNodeWrittenEvent), 'OCP\\Files\\Event...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'OCP\\Files\\Event...', Object(OCP\Files\Events\Node\BeforeNodeWrittenEvent))
#8 /var/www/html/lib/private/EventDispatcher/EventDispatcher.php(94): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(OCP\Files\Events\Node\BeforeNodeWrittenEvent), 'OCP\\Files\\Event...')
#9 /var/www/html/lib/private/EventDispatcher/EventDispatcher.php(106): OC\EventDispatcher\EventDispatcher->dispatch('OCP\\Files\\Event...', Object(OCP\Files\Events\Node\BeforeNodeWrittenEvent))
#10 /var/www/html/lib/private/Files/Node/HookConnector.php(100): OC\EventDispatcher\EventDispatcher->dispatchTyped(Object(OCP\Files\Events\Node\BeforeNodeWrittenEvent))
#11 /var/www/html/lib/private/legacy/OC_Hook.php(105): OC\Files\Node\HookConnector->write(Array)
#12 /var/www/html/lib/private/Files/View.php(1270): OC_Hook::emit('OC_Filesystem', 'write', Array)
#13 /var/www/html/lib/private/Files/View.php(1144): OC\Files\View->runHooks(Array, '[Path]...')
#14 /var/www/html/lib/private/Files/View.php(680): OC\Files\View->basicOperation('file_put_conten...', '[Path]...', Array, '{\n    "id": "[Restoring-Point-ID]...')
#15 /var/www/html/lib/private/Files/Node/File.php(73): OC\Files\View->file_put_contents('/ncp/files/GGG-...', '{\n    "id": "[Restoring-Point-ID]...')
#16 /var/www/html/custom_apps/backup/lib/Service/ExternalFolderService.php(223): OC\Files\Node\File->putContent('{\n    "id": "[Restoring-Point-ID]...')
#17 /var/www/html/custom_apps/backup/lib/Service/ExternalFolderService.php(388): OCA\Backup\Service\ExternalFolderService->getRestoringPoint(Object(OCA\Backup\Model\ExternalFolder), '[Restoring-Point-ID]...', true)
#18 /var/www/html/custom_apps/backup/lib/Service/UploadService.php(318): OCA\Backup\Service\ExternalFolderService->confirmPoint(Object(OCA\Backup\Model\ExternalFolder), Object(OCA\Backup\Model\RestoringPoint))
#19 /var/www/html/custom_apps/backup/lib/Service/UploadService.php(178): OCA\Backup\Service\UploadService->uploadToExternalFolder(Object(OCA\Backup\Model\RestoringPoint))
#20 /var/www/html/custom_apps/backup/lib/Command/PointUpload.php(143): OCA\Backup\Service\UploadService->uploadPoint(Object(OCA\Backup\Model\RestoringPoint))
#21 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\Backup\Command\PointUpload->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Backup\Command\PointUpload), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/console.php(100): OC\Console\Application->run()
#28 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

With Nextcloud Version 25, 26 and 27, I didn't have such issues. 
I am using the Docker image "nextcloud:28.0.3".
I am using backup app version "1.4.0".

**Comment by hammy1988** [comment]
The previous issue had a similar problem. I believe this could have the same cause. Issue #635

**Comment by hammy1988** [comment]
Yesterday, I updated to Nextcloud version 28.0.4. Since then, the error hasn't occurred anymore. Even with the 'Versions' app activated, the backup is working again.
